### ISSUE TITLE
bigwhoop.py crashes when run on raspberry pi 1 even with rtl-sdr installed

### ISSUE THREAD

**Issue by amki** [aerospaceresearch/DGSN_bigwhoop#1]
I'm running a Raspberry Pi (1 Model B) with a  Rafael Micro R820T tuner attached and rtl_tcp works pretty good.
Even though I installed pyrtlsdr from https://github.com/roger-/pyrtlsdr and rtl-sdr from git://git.osmocom.org/rtl-sdr.git I get the following:

python bigwhoop.py
Traceback (most recent call last):
  File "bigwhoop.py", line 4, in <module>
    from rtlsdr import RtlSdr
  File "/usr/local/lib/python2.7/dist-packages/rtlsdr/**init**.py", line 18, in <module>
    try:                from  librtlsdr import librtlsdr
  File "/usr/local/lib/python2.7/dist-packages/rtlsdr/librtlsdr.py", line 52, in <module>
    f = librtlsdr.rtlsdr_get_device_count
  File "/usr/lib/python2.7/ctypes/**init**.py", line 378, in **getattr**
    func = self.**getitem**(name)
  File "/usr/lib/python2.7/ctypes/**init**.py", line 383, in **getitem**
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: rtlsdr_get_device_count

**Comment by 3835** [comment]
Hi! 
I have a similar problem on my RPi (model B+). Rtl dongle works fine with another app (for example dump1090, modeSdeco2, rtl_power) but bigwhoop generate error:

`Traceback (most recent call last):`
`File "bigwhoop.py", line 4, in <module>`
`from rtlsdr import RtlSdr`
`ImportError: No module named rtlsdr`

**Comment by hornig** [comment]
hi there, thanks for the comments! That will help to find the cause for it.
We just need to fine someone with Raspis, because our few people in Stuttgart don't have one, so we cannot check for ourselves. Do you know a good Raspi community, where we could ask for help?

**Comment by bnt2025** [comment]
I have a couple of Raspis. I am very willing to help. Tell me what you need.

**Comment by amki** [comment]
I don't think you will find that many Raspberry Pis laying around with rtl-sdr devices on them, but the Raspberry Pi I had the problem with is online 24/7 and has the rtl-sdr on it. I could give you (root) access via ssh if you supply a public key. (Standard raspbian is running)

**Comment by hornig** [comment]
I already started and asked here https://www.raspberrypi.org/forums/viewtopic.php?f=32&t=109670 for possible help.
Have you been able to narrow it down where we could have a test with new/altered code?

**Comment by hornig** [comment]
@3835 could it be, that you don't have the pyrtlsd library installed? Because when it gives you an error at that line where the import pyrtlsdr is done, then it seems your python cannot find it in the lib folder.
Did you already download it, because we don't have that in our github repo. (And I now speculate that dump1090 and the other programmes you mentioned simply bundle that)
if not you can use "pip install pyrtlsdr" to download it and afterwards you come here again and tell us, if that worked for you.
Best regards, Andreas

**Comment by ghost** [comment]
@hornig Thanks for your feedback, I have been having the same issue with my Debian Wheezy servers so it could be a general problem with Debian based OS's. I have installed pyrtlsd like you suggested which has solved the origional import error on line 7, however the script is now complaining of an issue with line 14 which I guess is where it is importing requests? Hopefully this helps a little:  
Traceback (most recent call last):
  File "bigwhoop.py", line 14, in <module>
    import requests
ImportError: No module named requests

Kind Regards, Dan
